import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
// const test = (process.argv[2] === 'test' || process.argv[3] === 'test');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [ 'src/main.ts' ],
	bundle: true,
	// minify: prod,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lexer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: false,
	target: 'ES2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: '.',
}).catch(() => process.exit(1));

if (prod) {
	await context.rebuild();
	process.exit(0);
}
else {
	await context.watch();
}
